"""GitHub integration: PR creation, code search, recent commits."""
import logging
import uuid

from app.config import settings

logger = logging.getLogger(__name__)


class GitHubService:
    def __init__(self):
        from github import Github
        self.gh = Github(settings.github_token)
        self.default_repo = settings.github_repo

    async def create_fix_pr(self, incident, rca) -> str:
        """Create a GitHub PR with the proposed fix description."""
        import asyncio

        return await asyncio.get_event_loop().run_in_executor(
            None, self._create_fix_pr_sync, incident, rca
        )

    def _create_fix_pr_sync(self, incident, rca) -> str:
        repo = self.gh.get_repo(self.default_repo)
        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha

        branch_name = f"sre-ai/fix/{incident.id[:8]}"
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

        pr_content = self._render_pr_content(incident, rca)
        repo.create_file(
            path=f".sre-ai/incidents/{incident.id[:8]}/INVESTIGATION.md",
            message=f"chore(sre-ai): investigation report for {incident.title[:60]}",
            content=pr_content,
            branch=branch_name,
        )

        pr = repo.create_pull(
            title=f"[sre.ai] Fix: {incident.title[:70]}",
            body=self._render_pr_body(incident, rca),
            head=branch_name,
            base=default_branch,
        )
        pr.add_to_labels("sre-ai", "incident")
        return pr.html_url

    def _render_pr_content(self, incident, rca) -> str:
        return f"""# sre.ai Investigation Report

## Incident
- **ID**: {incident.id}
- **Title**: {incident.title}
- **Service**: {incident.service_name or 'unknown'}
- **Severity**: {incident.severity}
- **Triggered At**: {incident.triggered_at}

## Root Cause
{rca.root_cause}

## Proposed Fix
{rca.pr_description or 'See recommended actions below.'}

## Recommended Actions
{chr(10).join(f"- [{a.get('priority', '').upper()}] {a.get('action', '')}" for a in (rca.recommended_actions or []))}

---
*Generated by sre.ai | Confidence: {rca.confidence}*
"""

    def _render_pr_body(self, incident, rca) -> str:
        return f"""## sre.ai Automated Investigation

**Incident**: {incident.title}
**Service**: `{incident.service_name or 'unknown'}`
**Confidence**: {rca.confidence}

### Root Cause
{rca.root_cause}

### Proposed Fix
{rca.pr_description or '_No specific code fix identified. See investigation report._'}

### Evidence Summary
{rca.summary[:1500] if rca.summary else '_No summary available._'}

---
> This PR was automatically generated by [sre.ai](https://github.com/Jung028/sre.ai).
> Review and merge after human validation.
"""

    async def get_recent_commits(self, service: str, hours_back: int = 24) -> dict:
        import asyncio

        return await asyncio.get_event_loop().run_in_executor(
            None, self._get_recent_commits_sync, service, hours_back
        )

    def _get_recent_commits_sync(self, service: str, hours_back: int) -> dict:
        from datetime import datetime, timedelta, timezone

        repo = self.gh.get_repo(self.default_repo)
        since = datetime.now(timezone.utc) - timedelta(hours=hours_back)
        commits = repo.get_commits(since=since)
        return {
            "service": service,
            "commits": [
                {
                    "sha": c.sha[:8],
                    "message": c.commit.message.split("\n")[0],
                    "author": c.commit.author.email,
                    "timestamp": c.commit.author.date.isoformat(),
                }
                for c in list(commits)[:20]
            ],
        }

    async def search_code(self, query: str, repo: str | None = None) -> dict:
        import asyncio

        return await asyncio.get_event_loop().run_in_executor(
            None, self._search_code_sync, query, repo
        )

    def _search_code_sync(self, query: str, repo: str | None) -> dict:
        search_query = query
        target_repo = repo or self.default_repo
        if target_repo:
            search_query = f"{query} repo:{target_repo}"

        results = self.gh.search_code(search_query)
        return {
            "query": query,
            "results": [
                {"path": r.path, "repo": r.repository.full_name}
                for r in list(results)[:10]
            ],
        }
