import type { TraceData } from "./types";

export const MOCK_TRACES: Record<string, TraceData> = {
  "4bf92f3577b34da6a3ce929d0e0e4736": {
    traceId: "4bf92f3577b34da6a3ce929d0e0e4736",
    incidentId: "inc-001",
    service: "payment-service",
    startTime: "2026-04-10T10:05:08Z",
    durationMs: 4820,
    nodes: [
      { id: "api-gateway", label: "api-gateway", type: "service", status: "ok", depth: 0, indexInDepth: 0 },
      { id: "payment-service", label: "payment-service", type: "service", status: "error", depth: 1, indexInDepth: 0 },
      { id: "fraud-service", label: "fraud-service", type: "service", status: "ok", depth: 2, indexInDepth: 0 },
      { id: "redis-cache", label: "redis-cache", type: "cache", status: "ok", depth: 2, indexInDepth: 1 },
      { id: "postgres-pool", label: "postgres-pool", type: "database", status: "error", depth: 2, indexInDepth: 2 },
    ],
    edges: [
      { source: "api-gateway", target: "payment-service", label: "POST /charge", status: "error" },
      { source: "payment-service", target: "fraud-service", label: "check()", status: "ok" },
      { source: "payment-service", target: "redis-cache", label: "GET session", status: "ok" },
      { source: "payment-service", target: "postgres-pool", label: "INSERT tx", status: "error" },
    ],
    spans: [
      {
        spanId: "span-001",
        parentSpanId: null,
        service: "api-gateway",
        operation: "POST /api/v1/charge",
        startMs: 0,
        durationMs: 4820,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Received POST /api/v1/charge from 10.0.1.42" },
          { offsetMs: 4810, level: "error", message: "Upstream payment-service returned 503 Service Unavailable" },
        ],
        tags: { "http.method": "POST", "http.status_code": "503" },
      },
      {
        spanId: "span-002",
        parentSpanId: "span-001",
        service: "payment-service",
        operation: "processCharge()",
        startMs: 12,
        durationMs: 4795,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Processing charge: amount=99.00 currency=USD" },
          { offsetMs: 15, level: "debug", message: "Fetching session token from Redis" },
          { offsetMs: 28, level: "info", message: "Session valid, proceeding to fraud check" },
          { offsetMs: 310, level: "info", message: "Fraud check passed (score=0.02)" },
          { offsetMs: 315, level: "info", message: "Acquiring DB connection from pool (size=5, active=5)" },
          { offsetMs: 4780, level: "error", message: "FATAL: remaining connection slots are reserved for replication. Pool exhausted after 4465ms wait." },
          { offsetMs: 4790, level: "error", message: "Failed to persist transaction — throwing PaymentException" },
        ],
        tags: { "db.pool.size": "5", "db.pool.active": "5" },
      },
      {
        spanId: "span-003",
        parentSpanId: "span-002",
        service: "fraud-service",
        operation: "evaluate()",
        startMs: 40,
        durationMs: 268,
        status: "ok",
        logs: [
          { offsetMs: 0, level: "info", message: "Evaluating transaction risk: user_id=u-8821, amount=99.00" },
          { offsetMs: 250, level: "info", message: "Risk score: 0.02 (LOW) — approved" },
        ],
        tags: { "fraud.score": "0.02", "fraud.decision": "approved" },
      },
      {
        spanId: "span-004",
        parentSpanId: "span-002",
        service: "redis-cache",
        operation: "GET session:u-8821",
        startMs: 28,
        durationMs: 4,
        status: "ok",
        logs: [
          { offsetMs: 0, level: "debug", message: "GET session:u-8821" },
          { offsetMs: 3, level: "debug", message: "HIT — TTL 847s remaining" },
        ],
        tags: { "cache.hit": "true" },
      },
      {
        spanId: "span-005",
        parentSpanId: "span-002",
        service: "postgres-pool",
        operation: "INSERT transactions",
        startMs: 328,
        durationMs: 4465,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Waiting for available connection (pool_size=5, checked_out=5)" },
          { offsetMs: 1000, level: "warn", message: "Connection wait exceeded 1000ms — pool still exhausted" },
          { offsetMs: 2000, level: "warn", message: "Connection wait exceeded 2000ms" },
          { offsetMs: 3000, level: "warn", message: "Connection wait exceeded 3000ms" },
          { offsetMs: 4000, level: "warn", message: "Connection wait exceeded 4000ms" },
          { offsetMs: 4465, level: "error", message: "FATAL: remaining connection slots are reserved for replication" },
        ],
        tags: { "db.system": "postgresql", "db.pool.size": "5", "error": "true" },
      },
    ],
  },

  "a3c2b1d4e5f6789012345678abcdef01": {
    traceId: "a3c2b1d4e5f6789012345678abcdef01",
    incidentId: "inc-002",
    service: "auth-service",
    startTime: "2026-04-12T09:42:11Z",
    durationMs: 4312,
    nodes: [
      { id: "api-gateway", label: "api-gateway", type: "service", status: "ok", depth: 0, indexInDepth: 0 },
      { id: "auth-service", label: "auth-service", type: "service", status: "slow", depth: 1, indexInDepth: 0 },
      { id: "postgres-auth", label: "postgres-auth", type: "database", status: "slow", depth: 2, indexInDepth: 0 },
      { id: "redis-sessions", label: "redis-sessions", type: "cache", status: "ok", depth: 2, indexInDepth: 1 },
    ],
    edges: [
      { source: "api-gateway", target: "auth-service", label: "POST /login", status: "slow" },
      { source: "auth-service", target: "postgres-auth", label: "SELECT user", status: "slow" },
      { source: "auth-service", target: "redis-sessions", label: "SET session", status: "ok" },
    ],
    spans: [
      {
        spanId: "span-a01",
        parentSpanId: null,
        service: "api-gateway",
        operation: "POST /api/v1/auth/login",
        startMs: 0,
        durationMs: 4312,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "Received POST /api/v1/auth/login" },
          { offsetMs: 4300, level: "warn", message: "Request completed in 4312ms — SLO breach (threshold: 500ms)" },
        ],
        tags: { "http.method": "POST", "http.status_code": "200" },
      },
      {
        spanId: "span-a02",
        parentSpanId: "span-a01",
        service: "auth-service",
        operation: "authenticateUser()",
        startMs: 8,
        durationMs: 4288,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "Authenticating user: admin@acme.com" },
          { offsetMs: 5, level: "debug", message: "Initiating DB query for user record" },
          { offsetMs: 4180, level: "warn", message: "DB query returned after 4175ms (expected <50ms)" },
          { offsetMs: 4195, level: "info", message: "Password verified, creating session" },
        ],
        tags: { "auth.method": "password" },
      },
      {
        spanId: "span-a03",
        parentSpanId: "span-a02",
        service: "postgres-auth",
        operation: "SELECT users WHERE email",
        startMs: 13,
        durationMs: 4175,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "SELECT id, email, password_hash FROM users WHERE email=$1" },
          { offsetMs: 100, level: "warn", message: "Sequential scan on users table — missing index on email column" },
          { offsetMs: 4175, level: "warn", message: "Query completed via Seq Scan: 1.2M rows scanned, returned 1 row" },
        ],
        tags: { "db.system": "postgresql", "db.statement": "SELECT", "db.rows_examined": "1200000" },
      },
      {
        spanId: "span-a04",
        parentSpanId: "span-a02",
        service: "redis-sessions",
        operation: "SET session:tok-991a",
        startMs: 4205,
        durationMs: 3,
        status: "ok",
        logs: [
          { offsetMs: 0, level: "debug", message: "SET session:tok-991a EX 3600" },
          { offsetMs: 2, level: "debug", message: "OK" },
        ],
        tags: { "cache.ttl": "3600" },
      },
    ],
  },

  "7f1e3d2c4b5a6978091234567890abcd": {
    traceId: "7f1e3d2c4b5a6978091234567890abcd",
    incidentId: "inc-003",
    service: "notification-service",
    startTime: "2026-04-10T07:02:14Z",
    durationMs: 1840,
    nodes: [
      { id: "order-service", label: "order-service", type: "service", status: "ok", depth: 0, indexInDepth: 0 },
      { id: "notification-worker", label: "notification-worker", type: "service", status: "error", depth: 1, indexInDepth: 0 },
      { id: "handlebars-renderer", label: "handlebars-renderer", type: "service", status: "error", depth: 2, indexInDepth: 0 },
      { id: "sqs-notifications", label: "sqs-notifications", type: "queue", status: "slow", depth: 2, indexInDepth: 1 },
    ],
    edges: [
      { source: "order-service", target: "notification-worker", label: "send(email)", status: "error" },
      { source: "notification-worker", target: "handlebars-renderer", label: "render(template)", status: "error" },
      { source: "notification-worker", target: "sqs-notifications", label: "NACK → retry", status: "slow" },
    ],
    spans: [
      {
        spanId: "span-n01",
        parentSpanId: null,
        service: "order-service",
        operation: "sendOrderConfirmation()",
        startMs: 0,
        durationMs: 1840,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Enqueuing order confirmation email: order_id=ORD-48821" },
          { offsetMs: 1830, level: "error", message: "Message NACK'd by notification-worker, returned to SQS for retry" },
        ],
        tags: { "messaging.system": "sqs" },
      },
      {
        spanId: "span-n02",
        parentSpanId: "span-n01",
        service: "notification-worker",
        operation: "processMessage()",
        startMs: 40,
        durationMs: 1790,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Dequeued message: order_id=ORD-48821 template=order_confirmation_v2" },
          { offsetMs: 10, level: "debug", message: "Loading template: order_confirmation_v2.hbs" },
          { offsetMs: 85, level: "error", message: "HandlebarsException: Parse error at position 142: Unexpected token '#'" },
          { offsetMs: 86, level: "error", message: "Template render failed — NACKing message" },
        ],
        tags: { "template": "order_confirmation_v2.hbs" },
      },
      {
        spanId: "span-n03",
        parentSpanId: "span-n02",
        service: "handlebars-renderer",
        operation: "render(order_confirmation_v2)",
        startMs: 55,
        durationMs: 30,
        status: "error",
        logs: [
          { offsetMs: 0, level: "debug", message: "Parsing template: order_confirmation_v2.hbs" },
          { offsetMs: 28, level: "error", message: "Unclosed block helper '#if' at position 142 — template is malformed" },
        ],
        tags: { "template.name": "order_confirmation_v2.hbs", "error": "true" },
      },
      {
        spanId: "span-n04",
        parentSpanId: "span-n02",
        service: "sqs-notifications",
        operation: "NACK → ChangeMessageVisibility",
        startMs: 90,
        durationMs: 1700,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "warn", message: "NACK — changing message visibility (retry delay: 30s)" },
          { offsetMs: 1700, level: "warn", message: "Message will be retried. ApproximateReceiveCount: 1284" },
        ],
        tags: { "messaging.system": "sqs", "messaging.retry_count": "1284" },
      },
    ],
  },

  "b2c3d4e5f6a1789056789012345678ab": {
    traceId: "b2c3d4e5f6a1789056789012345678ab",
    incidentId: "inc-004",
    service: "api-gateway",
    startTime: "2026-04-09T08:14:04Z",
    durationMs: 2100,
    nodes: [
      { id: "api-gateway", label: "api-gateway", type: "service", status: "error", depth: 0, indexInDepth: 0 },
      { id: "user-service", label: "user-service", type: "service", status: "error", depth: 1, indexInDepth: 0 },
      { id: "postgres-users", label: "postgres-users", type: "database", status: "ok", depth: 2, indexInDepth: 0 },
    ],
    edges: [
      { source: "api-gateway", target: "user-service", label: "GET /profile", status: "error" },
      { source: "user-service", target: "postgres-users", label: "SELECT user", status: "ok" },
    ],
    spans: [
      {
        spanId: "span-g01",
        parentSpanId: null,
        service: "api-gateway",
        operation: "GET /api/v1/users/profile",
        startMs: 0,
        durationMs: 2100,
        status: "error",
        logs: [
          { offsetMs: 0, level: "info", message: "Routing GET /api/v1/users/profile → user-service:8080" },
          { offsetMs: 92, level: "error", message: "upstream connect error — connection refused (user-service:8080)" },
          { offsetMs: 95, level: "error", message: "Returning 502 Bad Gateway to client" },
        ],
        tags: { "http.status_code": "502" },
      },
      {
        spanId: "span-g02",
        parentSpanId: "span-g01",
        service: "user-service",
        operation: "OOMKilled restart",
        startMs: 5,
        durationMs: 2090,
        status: "error",
        logs: [
          { offsetMs: 0, level: "error", message: "Container received SIGKILL — OOM kill event (memory limit: 512Mi)" },
          { offsetMs: 5, level: "info", message: "Pod user-service-7d4b9f8c6-xk2pq terminated" },
          { offsetMs: 10, level: "info", message: "Kubernetes scheduling replacement pod" },
          { offsetMs: 1200, level: "info", message: "New pod user-service-7d4b9f8c6-mn8ql started" },
          { offsetMs: 2080, level: "info", message: "Readiness probe passed after 2090ms — pod marked ready" },
        ],
        tags: { "k8s.event": "OOMKilled", "k8s.memory_limit": "512Mi" },
      },
    ],
  },

  "9e8d7c6b5a4312f0abcdef0123456789": {
    traceId: "9e8d7c6b5a4312f0abcdef0123456789",
    incidentId: "inc-005",
    service: "search-service",
    startTime: "2026-04-08T14:31:05Z",
    durationMs: 8240,
    nodes: [
      { id: "api-gateway", label: "api-gateway", type: "service", status: "ok", depth: 0, indexInDepth: 0 },
      { id: "search-service", label: "search-service", type: "service", status: "slow", depth: 1, indexInDepth: 0 },
      { id: "elasticsearch", label: "elasticsearch", type: "database", status: "slow", depth: 2, indexInDepth: 0 },
      { id: "redis-search", label: "redis-search", type: "cache", status: "ok", depth: 2, indexInDepth: 1 },
    ],
    edges: [
      { source: "api-gateway", target: "search-service", label: "GET /search", status: "slow" },
      { source: "search-service", target: "elasticsearch", label: "wildcard query", status: "slow" },
      { source: "search-service", target: "redis-search", label: "cache miss", status: "ok" },
    ],
    spans: [
      {
        spanId: "span-s01",
        parentSpanId: null,
        service: "api-gateway",
        operation: "GET /api/v1/search",
        startMs: 0,
        durationMs: 8240,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "GET /api/v1/search?q=wireless+headphones" },
          { offsetMs: 8230, level: "warn", message: "Response in 8240ms — SLO breach (threshold: 500ms)" },
        ],
        tags: { "http.status_code": "200" },
      },
      {
        spanId: "span-s02",
        parentSpanId: "span-s01",
        service: "search-service",
        operation: "search(q=wireless headphones)",
        startMs: 6,
        durationMs: 8228,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "Search query: 'wireless headphones'" },
          { offsetMs: 2, level: "debug", message: "Checking cache: search:wireless+headphones" },
          { offsetMs: 8, level: "debug", message: "Cache MISS — querying Elasticsearch" },
          { offsetMs: 10, level: "debug", message: "Building wildcard query: { wildcard: { name: '*wireless headphones*' } }" },
          { offsetMs: 8220, level: "warn", message: "Elasticsearch query took 8210ms — full index scan detected" },
        ],
        tags: { "search.query_type": "wildcard" },
      },
      {
        spanId: "span-s03",
        parentSpanId: "span-s02",
        service: "redis-search",
        operation: "GET search:wireless+headphones",
        startMs: 8,
        durationMs: 4,
        status: "ok",
        logs: [
          { offsetMs: 0, level: "debug", message: "GET search:wireless+headphones" },
          { offsetMs: 3, level: "debug", message: "MISS" },
        ],
        tags: { "cache.hit": "false" },
      },
      {
        spanId: "span-s04",
        parentSpanId: "span-s02",
        service: "elasticsearch",
        operation: "search (wildcard)",
        startMs: 18,
        durationMs: 8210,
        status: "slow",
        logs: [
          { offsetMs: 0, level: "info", message: "Executing wildcard query on products index (2.8M documents)" },
          { offsetMs: 100, level: "warn", message: "Query plan: full index scan — wildcard queries do not use inverted index" },
          { offsetMs: 8200, level: "warn", message: "Scan complete: 2,800,000 docs examined, 847 matched. Took 8210ms." },
        ],
        tags: { "db.system": "elasticsearch", "db.docs_examined": "2800000", "db.query_type": "wildcard" },
      },
    ],
  },
};
